### ISSUE TITLE
[Bug] Issue when creating report in xml format

### ISSUE THREAD

**Issue by bushra2001** [saeeddhqan/Maryam#90] opened 2021-03-21 18:45 UTC
I would like to fix the following issue. 

https://user-images.githubusercontent.com/61081924/111920145-3818ee80-8aaf-11eb-8014-4c68d07d9108.mp4

**Comment by saeeddhqan** [comment] 2021-03-21 19:18
@bushra2001 do you want to be part of the contributors?

**Comment by bushra2001** [comment] 2021-03-21 19:21
Yes, I want to contribute to this project.

**Comment by saeeddhqan** [comment] 2021-03-21 19:25
#owasp-maryam this is the slack channel. join us, read the ideas and previous messages to get acquainted with the procedure.

**Comment by z3y50n** [comment] 2021-03-21 19:36
> I would like to fix the following issue.
> video_gsoc.mp4

The video seems broken. Could you either reupload it or explain the issue a bit more?

**Comment by bushra2001** [comment] 2021-03-21 19:45
> > I would like to fix the following issue.
> > video_gsoc.mp4
> 
> The video seems broken. Could you either reupload it or explain the issue a bit more?

Try to watch video with full screen. I am trying to convert the video into gif. 
Issue: When I am trying to generate the report in xml format, it is showing me error.

**Comment by bushra2001** [comment] 2021-03-21 20:18
> #owasp-maryam this is the slack channel. join us, read the ideas and previous messages to get acquainted with the procedure.

I am unable to find slack channel, can you send me an invite?
If you approve, should I start working on this issue?

**Comment by z3y50n** [comment] 2021-03-21 20:45
I have sent you an invitation to your email

**Comment by saeeddhqan** [comment] 2021-03-22 11:29
Do it with the dns_search output and let me know.

**Comment by bushra2001** [comment] 2021-03-22 21:08
> Do it with the dns_search output and let me know.

Dns_search is not displaying an error because it is dictionary within dictionary. Only those modules, which are single dictionary are displaying errors. I have resolved this bug, working on pr.

**Comment by saeeddhqan** [comment] 2021-03-22 22:02
It's totally not a bug. the input should have a key. You can fix it with a by-default key.
Beware any change can make lots of problems in the output functions.
Therefore, test the changes as far as you can.
Thank you

**Comment by bushra2001** [comment] 2021-03-23 11:28
> It's totally not a bug. the input should have a key. You can fix it with a by-default key.
> Beware any change can make lots of problems in the output functions.
> Therefore, test the changes as far as you can.
> Thank you

Key problem was resolved easily, these special characters ( $&<>!) are causing problems.
This problem is occurring only in cve_search and onion search modules. If I replace them, it would change the urls. Can you kindly guide me what I should do with them, your suggestions will be highly appreciated. 

![maryam_error](https://user-images.githubusercontent.com/61081924/112139480-a0251d00-8bf4-11eb-82d3-7b21f14fc379.png)

**Comment by bushra2001** [comment] 2021-03-23 12:45
The output is coming as follows. I have test the changes with the following commands;

report xml dns_search osint/dns_search example.com
report xml docs osint/email_search microsoft.com
report xml wapps footprint/wapps owasp.org
report xml entry_points footprint/entry_points example.com
report xml social_nets osint/social_nets @owasp
report xml suggestion osint/suggest amazon
report xml crawl_pages footprint/crawl_pages owasp.org
report xml onion_search osint/onion_search amazon

Is it fine, any suggestions will be appreciated. If you approve then I will create a pr.

![xml-fixed](https://user-images.githubusercontent.com/61081924/112148292-84734400-8bff-11eb-9dbe-78f7ed50383c.png)

**Comment by saeeddhqan** [comment] 2021-03-23 12:52
Make a PR.

**Comment by saeeddhqan** [comment] 2021-03-23 21:31
Fixed by #97

**Closed as completed by saeeddhqan** 2021-03-23 21:31 UTC
Labels: bug
